Repository noteu/noteu-separate, pull requests merged in 2023-12, with the labels that each got.

#4 #3 feat : RestController 변경
  back/noteu/src/main/java/com/noteu/noteu/chat/controller/ChatController.java
  back/noteu/src/main/java/com/noteu/noteu/chat/controller/ChatRoomController.java
  back/noteu/src/main/java/com/noteu/noteu/chat/entity/ChatParticipant.java
Labels: 🔥 backend

#6 JWT 인증으로 변경
  back/noteu/build.gradle
  back/noteu/src/main/java/com/noteu/noteu/config/SecurityConfig.java
  back/noteu/src/main/java/com/noteu/noteu/member/controller/AuthController.java
  back/noteu/src/main/java/com/noteu/noteu/member/controller/MemberController.java
  back/noteu/src/main/java/com/noteu/noteu/member/dto/AccountInfo.java
  back/noteu/src/main/java/com/noteu/noteu/member/dto/SignInDto.java
  back/noteu/src/main/java/com/noteu/noteu/member/security/config/CustomFilterConfig.java
  back/noteu/src/main/java/com/noteu/noteu/member/security/filter/JwtAuthenticationFilter.java
  back/noteu/src/main/java/com/noteu/noteu/member/security/filter/JwtVerificationFilter.java
  back/noteu/src/main/java/com/noteu/noteu/member/security/handler/MemberAccessDeniedHandler.java
  back/noteu/src/main/java/com/noteu/noteu/member/security/handler/MemberAuthenticationEntryPoint.java
  back/noteu/src/main/java/com/noteu/noteu/member/security/handler/MemberAuthenticationFailureHandler.java
  back/noteu/src/main/java/com/noteu/noteu/member/security/handler/MemberAuthenticationSuccessHandler.java
  back/noteu/src/main/java/com/noteu/noteu/member/security/utils/ErrorResponder.java
  back/noteu/src/main/java/com/noteu/noteu/member/security/utils/JwtUtils.java
Labels: 💫 feat, 🔥 backend

#9 자료실 조회수 컬럼 추가
  back/noteu/src/main/java/com/noteu/noteu/reference/converter/ReferenceRoomConverter.java
  back/noteu/src/main/java/com/noteu/noteu/reference/dto/ReferenceRoomDTO.java
  back/noteu/src/main/java/com/noteu/noteu/reference/dto/response/DetailResponseReferenceRoomDTO.java
  back/noteu/src/main/java/com/noteu/noteu/reference/dto/response/GetAllResponseReferenceRoomDTO.java
  back/noteu/src/main/java/com/noteu/noteu/reference/entity/ReferenceRoom.java
  back/noteu/src/main/java/com/noteu/noteu/reference/repository/ReferenceRoomRepository.java
  back/noteu/src/main/java/com/noteu/noteu/reference/service/ReferenceRoomService.java
  back/noteu/src/main/java/com/noteu/noteu/reference/service/impl/ReferenceRoomServiceImpl.java
Labels: 💫 feat, 🔥 backend

#10 ReferenceRoom RestController로 변경
  back/noteu/src/main/java/com/noteu/noteu/reference/controller/ReferenceRoomController.java
  back/noteu/src/main/java/com/noteu/noteu/reference/dto/request/AddRequestReferenceRoomDTO.java
  back/noteu/src/main/java/com/noteu/noteu/reference/dto/request/EditRequestReferenceRoomDTO.java
Labels: 💫 feat, 🔥 backend

#13 RestController 변경
  back/noteu/src/main/java/com/noteu/noteu/notice/controller/NoticeController.java
  back/noteu/src/main/java/com/noteu/noteu/subject/controller/SubjectController.java
  back/noteu/src/main/java/com/noteu/noteu/subject/controller/SubjectMemberController.java
  back/noteu/src/main/java/com/noteu/noteu/subject/dto/SubjectRequestDto.java
  back/noteu/src/main/java/com/noteu/noteu/subject/service/SubjectService.java
  back/noteu/src/main/java/com/noteu/noteu/subject/service/impl/SubjectServiceImpl.java
  back/noteu/src/main/java/com/noteu/noteu/task/controller/TaskCommentController.java
  back/noteu/src/main/java/com/noteu/noteu/task/controller/TaskController.java
  back/noteu/src/main/java/com/noteu/noteu/task/service/TaskService.java
  back/noteu/src/main/java/com/noteu/noteu/task/service/impl/TaskServiceImpl.java
Labels: 💫 feat, 🔥 backend

#15 로그인 구현
  back/noteu/src/main/java/com/noteu/noteu/config/SecurityConfig.java
  back/noteu/src/main/java/com/noteu/noteu/member/controller/AuthController.java
  back/noteu/src/main/java/com/noteu/noteu/member/security/handler/MemberAuthenticationFailureHandler.java
  front/src/common/api/auth.js
  front/src/common/context/useAuthContext.jsx
  front/src/pages/account/AccountWrapper.jsx
  front/src/pages/account/Login/LoginRequest.js
  front/src/pages/account/Login/index.jsx
  front/src/pages/account/Login/useLogin.js
Labels: 💫 feat, 🌈 frontend

#17 자료실 페이지 구현
  front/src/common/menu-items.js
  front/src/pages/apps/ReferenceRoom/Create/CreateReferenceRoom.jsx
  front/src/pages/apps/ReferenceRoom/Create/index.jsx
  front/src/pages/apps/ReferenceRoom/Detail/DetailReferenceRoom.jsx
  front/src/pages/apps/ReferenceRoom/Detail/Files.jsx
  front/src/pages/apps/ReferenceRoom/Detail/index.jsx
  front/src/pages/apps/ReferenceRoom/List/ListReferenceRoom.jsx
  front/src/pages/apps/ReferenceRoom/List/Table.jsx
  front/src/pages/apps/ReferenceRoom/List/index.jsx
  front/src/pages/apps/ReferenceRoom/hooks/index.js
  front/src/pages/apps/ReferenceRoom/hooks/useReferenceRoomForm.js
  front/src/pages/apps/ReferenceRoom/index.jsx
  front/src/pages/apps/index.jsx
Labels: 💫 feat, 🌈 frontend

#18 상세 페이지 조회 시 LazyInitializationException 발생 문제 해결
  back/noteu/src/main/java/com/noteu/noteu/reference/controller/ReferenceRoomController.java
  back/noteu/src/main/java/com/noteu/noteu/reference/converter/ReferenceRoomConverter.java
  back/noteu/src/main/java/com/noteu/noteu/reference/dto/response/DetailResponseReferenceRoomDTO.java
  back/noteu/src/main/java/com/noteu/noteu/reference/dto/response/ResponseReferenceDTO.java
  back/noteu/src/main/java/com/noteu/noteu/reference/service/ReferenceRoomService.java
  back/noteu/src/main/java/com/noteu/noteu/reference/service/impl/ReferenceRoomServiceImpl.java
Labels: 🐛 bug, ♻️ refactor, 🔥 backend

#20 자료실 Controller HttpStatus 반환값 수정
  back/noteu/src/main/java/com/noteu/noteu/reference/controller/ReferenceRoomController.java
Labels: ♻️ refactor, 🔥 backend

#22 과목 생성, 리스트
  front/src/common/menu-items.js
  front/src/pages/apps/Subject/Create/CreateSubject.jsx
  front/src/pages/apps/Subject/Create/index.jsx
  front/src/pages/apps/Subject/List/ProjectCard.jsx
  front/src/pages/apps/Subject/List/SubjectList.jsx
  front/src/pages/apps/Subject/List/index.jsx
  front/src/pages/apps/Subject/hooks/index.js
  front/src/pages/apps/Subject/hooks/useSubjectForm.js
  front/src/pages/apps/Subject/index.jsx
  front/src/pages/apps/index.jsx
Labels: 🌈 frontend

#23 자료실 상세 페이지, 게시글 작성 페이지 기능 추가
  front/src/components/CardTitle.jsx
  front/src/components/FileUploader/FileUploader.jsx
  front/src/components/FileUploader/useFileUploader.js
  front/src/components/Form/TextAreaInput.jsx
  front/src/pages/apps/ReferenceRoom/Create/CreateReferenceRoom.jsx
  front/src/pages/apps/ReferenceRoom/Detail/DetailReferenceRoom.jsx
  front/src/pages/apps/ReferenceRoom/Detail/Files.jsx
  front/src/pages/apps/ReferenceRoom/hooks/useReferenceRoomForm.js
Labels: 💫 feat, 🌈 frontend

#26 자료실 상세 페이지 내 Form onSubmit 내용 수정
  front/src/pages/apps/ReferenceRoom/Create/CreateReferenceRoom.jsx
  front/src/pages/apps/ReferenceRoom/hooks/useReferenceRoomForm.js
Labels: 🐛 bug, 🌈 frontend, ♻️ refactor

#27 자료실 게시글 삭제 시 이동 경로 수정
  front/src/pages/apps/ReferenceRoom/Detail/DetailReferenceRoom.jsx
Labels: 🐛 bug, 🌈 frontend, ♻️ refactor

#28 채팅추가
  back/noteu/ChatHttpRequest.http
  back/noteu/MemberHttpRequest.http
  back/noteu/src/main/java/com/noteu/noteu/chat/controller/ChatController.java
  back/noteu/src/main/java/com/noteu/noteu/chat/controller/ChatRoomController.java
  back/noteu/src/main/java/com/noteu/noteu/chat/dto/response/ChatMessageResponseDto.java
  back/noteu/src/main/java/com/noteu/noteu/chat/dto/response/ChatRoomInfoResponseDto.java
  back/noteu/src/main/java/com/noteu/noteu/chat/entity/ChatMessage.java
  back/noteu/src/main/java/com/noteu/noteu/chat/service/RestChatService.java
  back/noteu/src/main/java/com/noteu/noteu/chat/service/impl/RestChatServiceImpl.java
  back/noteu/src/main/java/com/noteu/noteu/chat/service/impl/SocketChatServiceImpl.java
  back/noteu/src/main/java/com/noteu/noteu/member/controller/MemberController.java
  back/noteu/src/main/resources/data.sql
  back/noteu/src/main/resources/static/js/task/add.js
  front/.eslintrc.cjs
  front/.gitignore
  front/package.json
  front/src/pages/apps/Chat/ChatApp.jsx
  front/src/pages/apps/Chat/ChatArea.jsx
  front/src/pages/apps/Chat/ChatUsers.jsx
  front/src/pages/apps/Chat/hooks/chat.js
  front/src/pages/apps/Chat/hooks/useChatApp.js
  front/src/pages/apps/Chat/hooks/useChatArea.js
  front/src/pages/apps/Chat/hooks/useChatUsers.js
  front/yarn.lock
Labels: 🌈 frontend

#31 회원가입, 마이페이지
  .DS_Store
  back/noteu/src/main/java/com/noteu/noteu/member/dto/SignUpDto.java
  back/noteu/src/main/java/com/noteu/noteu/member/service/MemberDetailsService.java
  back/noteu/src/main/resources/data.sql
  front/package.json
  front/src/assets/images/profile/default.png
  front/src/common/api/auth.js
  front/src/common/api/fake-backend.js
  front/src/components/Form/RadioInput.jsx
  front/src/components/Form/TextInput.jsx
  front/src/layouts/LeftSidebar.jsx
  front/src/layouts/Topbar/data.js
  front/src/layouts/Topbar/index.jsx
  front/src/pages/account/Login/LoginRequest.js
  front/src/pages/account/Login/extractClaims.js
  front/src/pages/account/Login/useLogin.js
  front/src/pages/account/Register/index.jsx
  front/src/pages/account/Register/useRegister.js
  front/src/pages/otherpages/Profile2/About.jsx
  front/src/pages/otherpages/Profile2/ProfilePage2.jsx
  front/src/pages/otherpages/Profile2/Settings.jsx
  front/src/pages/otherpages/Profile2/TimeLine.jsx
  front/src/pages/otherpages/Profile2/UserBox.jsx
  front/src/pages/otherpages/Profile2/fetchData.js
  front/yarn.lock
Labels: 💫 feat, 🌈 frontend, 🔥 backend

#32 QuestionPost RestController로 변경
  back/noteu/src/main/java/com/noteu/noteu/question/controller/QuestionPostController.java
  back/noteu/src/main/java/com/noteu/noteu/question/converter/QuestionPostConverter.java
  back/noteu/src/main/java/com/noteu/noteu/question/dto/response/DetailResponseQuestionPostDTO.java
  back/noteu/src/main/java/com/noteu/noteu/question/dto/response/GetAllResponseQuestionPostDTO.java
Labels: 💫 feat, 🔥 backend

#36 #34 feat : 질문게시판 조회수 컬럼 추가 및 목록 조회 시 댓글 수 전달
  back/noteu/src/main/java/com/noteu/noteu/question/controller/QuestionPostController.java
  back/noteu/src/main/java/com/noteu/noteu/question/converter/QuestionPostConverter.java
  back/noteu/src/main/java/com/noteu/noteu/question/dto/QuestionPostDTO.java
  back/noteu/src/main/java/com/noteu/noteu/question/dto/response/DetailResponseQuestionPostDTO.java
  back/noteu/src/main/java/com/noteu/noteu/question/dto/response/GetAllResponseQuestionPostDTO.java
  back/noteu/src/main/java/com/noteu/noteu/question/entity/QuestionPost.java
  back/noteu/src/main/java/com/noteu/noteu/question/repository/QuestionPostRepository.java
  back/noteu/src/main/java/com/noteu/noteu/question/service/QuestionPostService.java
  back/noteu/src/main/java/com/noteu/noteu/question/service/impl/QuestionPostServiceImpl.java
Labels: 💫 feat, 🔥 backend

#37 #35 feat: 프로필 변경
  back/noteu/.gitignore
  back/noteu/src/main/java/com/noteu/noteu/config/SecurityConfig.java
  back/noteu/src/main/java/com/noteu/noteu/member/controller/MemberController.java
  back/noteu/src/main/resources/data.sql
  back/noteu/src/main/resources/static/assets/profile/default.png
  front/src/common/api/auth.js
  front/src/components/Form/TextInput.jsx
  front/src/layouts/LeftSidebar.jsx
  front/src/layouts/Topbar/ProfileDropdown.jsx
  front/src/layouts/Topbar/data.js
  front/src/pages/account/AccountWrapper.jsx
  front/src/pages/account/Login/useLogin.js
  front/src/pages/otherpages/ChangeProfile/ChangeProfile.jsx
  front/src/pages/otherpages/ChangeProfile/index.jsx
  front/src/pages/otherpages/Profile2/ProfilePage2.jsx
  front/src/pages/otherpages/Profile2/Settings.jsx
  front/src/pages/otherpages/Profile2/UserBox.jsx
  front/src/pages/otherpages/index.jsx
Labels: 💫 feat, 🌈 frontend, 🔥 backend

#40 공지사항 게시판 구현
  back/noteu/src/main/java/com/noteu/noteu/notice/controller/NoticeController.java
  front/src/pages/apps/Notice/Create/CreateNotice.jsx
  front/src/pages/apps/Notice/Create/index.jsx
  front/src/pages/apps/Notice/Detail/DetailNotice.jsx
  front/src/pages/apps/Notice/Detail/index.jsx
  front/src/pages/apps/Notice/List/NoticeList.jsx
  front/src/pages/apps/Notice/List/Table.jsx
  front/src/pages/apps/Notice/List/index.jsx
  front/src/pages/apps/Notice/hooks/index.js
  front/src/pages/apps/Notice/hooks/useNoticeForm.js
  front/src/pages/apps/Notice/index.jsx
Labels: 💫 feat, 🌈 frontend

#45 과제 게시판 구현
  front/src/components/Form/CustomDatePicker.jsx
  front/src/pages/apps/Task/Create/CreateTask.jsx
  front/src/pages/apps/Task/Create/index.jsx
  front/src/pages/apps/Task/Details/DetailTask.jsx
  front/src/pages/apps/Task/Details/TaskComments.jsx
  front/src/pages/apps/Task/Details/index.jsx
  front/src/pages/apps/Task/List/ListTask.jsx
  front/src/pages/apps/Task/List/Table.jsx
  front/src/pages/apps/Task/List/index.jsx
  front/src/pages/apps/Task/hooks/index.js
  front/src/pages/apps/Task/hooks/useTaskForm.js
  front/src/pages/apps/Task/index.jsx
Labels: 💫 feat, 🌈 frontend

#53 #51 feat: Notice, Task Delete
  front/src/pages/apps/Notice/Detail/DetailNotice.jsx
  front/src/pages/apps/Task/Details/DetailTask.jsx
Labels: 💫 feat, 🌈 frontend

#54 #52 refactor: Notice, Task create -> url
  front/src/pages/apps/Notice/hooks/useNoticeForm.js
  front/src/pages/apps/Task/hooks/useTaskForm.js
Labels: 💫 feat, 🌈 frontend, ♻️ refactor

#56 #55 style: Task
  front/src/pages/apps/Task/List/ListTask.jsx
  front/src/pages/apps/Task/List/Table.jsx
  front/src/pages/apps/Task/index.jsx
Labels: 🌈 frontend

#61 QuestionComment RestController로 변환
  back/noteu/src/main/java/com/noteu/noteu/question/controller/QuestionCommentController.java
  back/noteu/src/main/java/com/noteu/noteu/question/converter/QuestionPostConverter.java
  back/noteu/src/main/java/com/noteu/noteu/question/dto/response/ResponseQuestionCommentDTO.java
  back/noteu/src/main/java/com/noteu/noteu/question/service/QuestionCommentService.java
  back/noteu/src/main/java/com/noteu/noteu/question/service/impl/QuestionCommentServiceImpl.java
Labels: 💫 feat, 🔥 backend

#63 공지사항, 과제, 과목 생성 버튼 역할별 숨기기
  front/src/pages/apps/Notice/List/NoticeList.jsx
  front/src/pages/apps/Subject/List/SubjectList.jsx
  front/src/pages/apps/Task/List/ListTask.jsx
Labels: 💫 feat, 🌈 frontend
